import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Logo from "@/components/Logo"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "HIII_Fit",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="header my-4 ">
          <Logo />
          <div className="ml-16 flex gap-4">
            <a className="menu-link" href="/crear-rutina">
              Nueva
            </a>
            <a className="menu-link" href="/ejecutar-rutina">
              Ejecutar
            </a>
            <a className="menu-link" href="/editar-rutina">
              Editar
            </a>
          </div>
        </nav>
        <main  style={{
          //  background: 'linear-gradient(to bottom, #382d2d, #e0ffe0)'
           background: '#382d2d'
         }}>{children}</main>
      </body>
    </html>
  )
}
